### ISSUE TITLE
MS03 Deliverables

### ISSUE THREAD

**Issue by TOtto-EclipseIR** [TOtto-EclipseIR/EIRC2#23]
* Strip back to Hello Console capability and add pieces one at a time:
  - [x] main.cpp
  - [x] Hello Console in a slot
  - [x] Command Line interpretation testing [#24]
  - [x] Reading input QFileInfoList
  - [x] Reading configuration from command line and merge with results
  - [ ] Output to Output/InputDir and Output/InputGreyDir
  - [ ] Begin rectangle finder ~[#26]~ [#33] **In MSVC toolchain plugin**
  - [ ] Begin [#8] eirXfr by splitting QtDebug to log instead of stdio
  - [ ] Output to MarkedFrameDir and RectangleFrameDir
  - [ ] Begin Candidate-Election process for frontal faces
  - [ ] Output to HeatmapDir, CandidateFrameDir
  - [ ] Output to DetectedFaceDir, MarkedFaceDir, CandidateFaceDir
  - [ ] Prepare for MS04

* Carryover from MS02
 - [ ] - Variable (Frontal Face)/Detect/MinQuality
   - [ ] - Methods TBD:
   - [ ] - Rough Quality score
   - [ ] - Frontal Face candidate election 
 - [ ] - Prepare for testing
   - GreyScale methods
     - [ ] - TRY_CONVERTTOFORMAT
     - [ ] - TRY_OPENCVTYPE2TYPE
     - [ ] - Homebrew
   - [ ] - New HeatMap Method 
 - [ ] - Handle Build Issues for Rel/Dbg Win32/~64~ [#1]
 * Refactor If2Console
   - [ ] - Move all Frame/Face output to If2Console class
   - [ ] - Change Area accumulator to Width
   - [ ] - Encode ER::ERResults into FaceCandidate VarPak
     * Map:
      * /Rank
        * 00/UnusedRects
        * 01/CandidateRect, Quality(count for now), RectList
        * ...
    * Array
      * 01.../CandidatrRect

* To be Completed:
 - [ ] - **Switch to old-style Aim8 face cascade**
 - [ ] - Redirect QtDebug and eirXfr output to log, todo files [#8]
 - [ ] - Split eirPixelImage to eirImage and eirMarker
 - [ ] - Comprehensive CommandLine handling [#24]
   - [ ] - Specification of input directories and files (local, not HTTP)
   - [ ] - Inclusion of configuration files (JSON?/INI) - See References below:
 - [ ] - Basic static Configuration values (from CommandLine) TBD

 * References
   - [Wikipedia: INI Files](https://en.wikipedia.org/wiki/INI_file)
   - [Python Standard Documentation _The Gold Standard?_](https://docs.python.org/3/library/configparser.html)
   - [Microsoft PrivateProfileString](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getprivateprofilestring?redirectedfrom=MSDN)
   - [Thayne McCombs](https://www.lucidchart.com/techblog/2018/07/16/why-json-isnt-a-good-configuration-language/) 
   - [MadMurphy _libconfini_ ](https://madmurphy.github.io/libconfini/html/libconfini.html)
   - [CODING HORROR: Was The Windows Registry a Good Idea?](https://blog.codinghorror.com/was-the-windows-registry-a-good-idea/)

**Comment by TOtto-EclipseIR** [comment]
Consider using 1 or 2 neighbors to get reasonable set of rectangles and then feature detection within each of them contributing to a blended Quality-Consistency/Congruence score.

**Comment by TOtto-EclipseIR** [comment]
Crash Reports via Felgo Hockey sample plugin.
[Felgo doc](https://felgo.com/doc/plugin-hockeyapp/)

**Comment by TOtto-EclipseIR** [comment]
* Roadmap
  - [ ] eirExe:CommandLine::expandDirectoriess(recurse)
  - [ ] If2Console
    - [ ] InitializeApplication
    - [ ] setupCommandLine
      - [ ] expandDirectories
    - [ ] getConfiguration
    - [ ] InitializeResources
      - [ ] rectFinder::initialize x 3 (OR 5)
    - [ ] startProcessing
    - [ ] nextFile
    - [ ] processFile
    - [ ] finishedProcessing
  - [ ] eirImage
    - [ ] outputImageQueue
    - [ ] imagePak
    - [ ] imageMarker
    - [ ] ...
  - [ ] eirExe
    - [ ] fileWriteQueue
  - [ ] eirRect
    - [ ] findRectangles
      - [ ] initialize(cascade)
      - [ ] setImage
      - [ ] configure
      - [ ] calculateParameters(configuration, imageSize)
      - [ ] detect
      - [ ] takeRectangles
  - [ ] eirFrame
    - [ ] candidateSelection
    - [ ] faceElection
    - [ ] faceCongruence
  - [ ] eirFace

**Comment by TOtto-EclipseIR** [comment]
# Development Needs & Notes:

* All interface between If2Console and RectFinder
  - [ ] LoadCascadeXmlFile(QFileInfo)
  - [ ] LoadCascade(QDomElement)
  - [ ] CloseCascade()
  - [ ] LoadImage(QByteArray)
  - [ ] ClearImage()
  - [ ] ClearResults()

* eirBase:VarPak, etc.
  * QObject interface 
    - [ ] emit changed(Id)
    - [ ] emit changed(QByteArray)
    - [ ] emit changed(int index)
    - [ ] emit changed(MultiName)

* eirImage:ImagePakObject

* eirRectDet library

* eirFrame library

* eirFace library

* Scratch Entity database
